import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Home, Trash2, Download } from "lucide-react";
import { toast } from "@/hooks/use-toast";

interface PatientAnalysis {
  id: number;
  date: string;
  patientName: string;
  harmony: number;
  measurements: Record<string, number>;
  notes: string;
  clinicalNotes?: string;
  visitHistory?: { date: string; harmony: number; notes: string }[];
}

export default function PatientArchive() {
  const [, navigate] = useLocation();
  const [patients, setPatients] = useState<PatientAnalysis[]>([]);
  const [expandedPatient, setExpandedPatient] = useState<number | null>(null);
  const [editingNotes, setEditingNotes] = useState<{ [key: number]: string }>({});

  useEffect(() => {
    const saved = localStorage.getItem("patientArchive");
    if (saved) setPatients(JSON.parse(saved));
  }, []);

  const updateClinicalNotes = (id: number, notes: string) => {
    const updated = patients.map((p) =>
      p.id === id ? { ...p, clinicalNotes: notes } : p
    );
    setPatients(updated);
    localStorage.setItem("patientArchive", JSON.stringify(updated));
    toast({ title: "Saved", description: "Clinical notes updated" });
  };

  const deletePatient = (id: number) => {
    const updated = patients.filter((p) => p.id !== id);
    setPatients(updated);
    localStorage.setItem("patientArchive", JSON.stringify(updated));
  };

  const exportReport = (patient: PatientAnalysis) => {
    const report = `PATIENT SMILE ANALYSIS REPORT
Date: ${patient.date}
Patient: ${patient.patientName}
Harmony Score: ${patient.harmony}/100

MEASUREMENTS:
${Object.entries(patient.measurements)
  .map(([k, v]) => `${k}: ${v.toFixed(1)}`)
  .join("\n")}

CLINICAL NOTES:
${patient.notes}

Generated by Lumina Ultra - Clinical DSD Platform`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${patient.patientName}_${patient.date}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-accent/5">
      <nav className="flex items-center justify-between px-6 py-4 border-b border-white/10 backdrop-blur-sm">
        <h1 className="font-heading font-bold text-white">Patient Archive</h1>
        <Button variant="ghost" size="icon" onClick={() => navigate("/")} className="text-white hover:bg-white/10">
          <Home className="w-5 h-5" />
        </Button>
      </nav>

      <div className="max-w-4xl mx-auto p-6 space-y-6">
        <div className="bg-blue-900/20 border border-blue-500/30 rounded-xl p-4">
          <p className="text-xs text-blue-200">
            💡 Patients are automatically added when you capture analysis in the AR Scanner. Click "Start Clinical Analysis" to add a new patient.
          </p>
          <Button onClick={() => navigate("/scanner")} className="mt-3 bg-primary hover:bg-primary/90 w-full">
            Open AR Scanner
          </Button>
        </div>

        <div className="space-y-3">
          {patients.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <p className="text-sm">No patients in archive yet. Add one above to get started.</p>
            </div>
          ) : (
            patients.map((patient) => (
              <div key={patient.id} className="bg-card/50 border border-white/10 rounded-lg overflow-hidden hover:bg-card/70 transition-all">
                <div className="p-4 space-y-3">
                  <button
                    onClick={() => setExpandedPatient(expandedPatient === patient.id ? null : patient.id)}
                    className="w-full text-left"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <h3 className="font-semibold text-white">{patient.patientName}</h3>
                        <p className="text-xs text-muted-foreground">{patient.date}</p>
                      </div>
                      <Badge
                        className={
                          patient.harmony >= 85
                            ? "bg-green-900/60 text-green-300"
                            : patient.harmony >= 70
                              ? "bg-yellow-900/60 text-yellow-300"
                              : "bg-red-900/60 text-red-300"
                        }
                      >
                        {patient.harmony}/100
                      </Badge>
                    </div>
                  </button>

                  <p className="text-xs text-white/70 bg-white/5 p-2 rounded">{patient.notes}</p>

                  {expandedPatient === patient.id && (
                    <div className="space-y-3 pt-3 border-t border-white/10">
                      <div>
                        <label className="text-xs font-semibold text-muted-foreground block mb-2">Clinical Notes</label>
                        <textarea
                          value={editingNotes[patient.id] ?? patient.clinicalNotes ?? ""}
                          onChange={(e) => setEditingNotes({ ...editingNotes, [patient.id]: e.target.value })}
                          onBlur={() => {
                            if (editingNotes[patient.id] !== undefined) {
                              updateClinicalNotes(patient.id, editingNotes[patient.id]);
                              const updated = { ...editingNotes };
                              delete updated[patient.id];
                              setEditingNotes(updated);
                            }
                          }}
                          className="w-full bg-white/10 border border-white/20 rounded px-2 py-2 text-xs text-white placeholder:text-white/50 outline-none focus:border-primary/50 resize-none"
                          rows={3}
                          placeholder="Add clinical observations, diagnosis, treatment plan..."
                        />
                      </div>
                    </div>
                  )}

                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => exportReport(patient)}
                      className="flex-1 text-xs"
                    >
                      <Download className="w-3 h-3 mr-1" />
                      Export
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => deletePatient(patient.id)}
                      className="text-red-400 hover:text-red-300 hover:border-red-400/50"
                    >
                      <Trash2 className="w-3 h-3" />
                    </Button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
